name: Library CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      BUILD_CONFIGURATION: Release
      
    # why these permissions? see: https://github.com/marketplace/actions/publish-test-results#permissions
    permissions:
      checks: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore

      - name: Unit Test
        run: dotnet test --configuration ${{ env.BUILD_CONFIGURATION }} --no-build --logger:trx

      - name: Publish Test Results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: '**/*.trx'

      - name: Pack
        run: dotnet pack --configuration ${{ env.BUILD_CONFIGURATION }} --no-build

      - name: Push to NuGet
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: |
          dotnet nuget push **/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate --no-symbols
